services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=admin'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - 27017:27017
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
  polling:
    depends_on:
      - mongodb
      - redis
    image: 'mgbramwell/polling:0-SNAPSHOT'
    ports:
      - 8080:8080
